version: "3.8"

services:
  
  web-next:
    build: Dockerfile
    container_name: next-web
    volumes:
      - ./:src/app
      - /src/app/node_modules
    ports:
      - 3000:3000
    environment:
        - CHOKIDAR_USEPOLLING=true  # Untuk file watching di Docker
        - WATCHPACK_POLLING=true    # Alternative untuk file watching
        - NODE_ENV=development
        - HOST=0.0.0.0
        - PORT=3000
        - NEXT_PUBLIC_BASE_URL=/
    stdin_open: true
    tty: true
